### ISSUE TITLE
So many things are broken

### ISSUE THREAD

**Issue by itsablast60** [MaximumADHD/sm64-roblox#7]
First of all, there's an invisible border that cant make me go a certain distance for some reason
Second spawns dont work
Third I cannot touch under blocks, there's just a big gap when i jump over it
fourth, non collidable blocks are touchable
Can someone please help me with this
also touching is broken i cant use touch commands

**Comment by MaximumADHD** [comment]
This codebase emulates the original behavior of Super Mario 64, limitations and all, 100% intentionally. These kinds of glitches are expected because there’s limited auxiliary information shared between SM64’s movement state machine and Roblox’s actual physical world setup.

You should not use this as a foundation for a modern platformer, it’s more of a novelty.

**Comment by itsablast60** [comment]
Oh damn alright

**Comment by MaximumADHD** [comment]
You can also make CanCollide work correctly if you write `rayParams.RespectsCanCollide = true` in the Util module.
